name: Deploy to s3
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build files
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - name: Deploy to s3
        env: 
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: 
          aws s3 cp . s3://philagov-vue-apps/jail-population-chart --recursive # change it
